Documentation Creation
stjude/CICERO pull request #40
Opened 2020-11-10 17:20 UTC by jordan-rash

- Created Github Action for GitHub Pages
- Started MkDocs documentation migration

Note: a lot of this code is boiler plate Mkdocs code

2020-11-11 02:44 UTC, claymcleod requested changes
I don't think the `site/` directory needs to be committed. The built site should only be available on the `gh-pages` branch.

2020-11-11 02:49 UTC, claymcleod commented
I can see it's working as intended here: https://github.com/jordan-rash/CICERO/tree/gh-pages. Maybe just remove that directory and add `site/` to the `.gitignore`.

2020-11-11 19:23 UTC, jordan-rash commented
Good catch.  Cleaned up all the tag alongs

2020-11-11 20:15 UTC, claymcleod approved these changes
LGTM

2020-11-16 23:26 UTC, jordan-rash commented
@adthrasher @claymcleod I don't have write access to merge this. It looks like a recent commit has formed a conflict.  Ill get that sorted and then push the update.

2020-11-16 23:43 UTC, adthrasher commented
Thanks @jordan-rash. I merged an outstanding PR earlier and that's probably what caused the conflict. Let me know when you're ready and I can do the merge.

2020-11-16 23:47 UTC, adthrasher approved these changes

2020-11-16 23:47 UTC, adthrasher commented on README.md
> +   <a href="https://stjudecloud.github.io/cicero/"><strong>Explore the docs »</strong></a>
This is actually under the `stjude` org and not the `stjudecloud` org.

2020-11-16 23:47 UTC, adthrasher commented on README.md
> +   <a href="https://github.com/stjudecloud/cicero/issues/new?assignees=&labels=&template=feature_request.md&title=Descriptive%20Title&labels=enhancement">Request Feature</a>
Same as above

2020-11-16 23:47 UTC, adthrasher commented on README.md
> +   <a href="https://github.com/stjudecloud/cicero/issues/new?assignees=&labels=&template=bug_report.md&title=Descriptive%20Title&labels=bug">Report Bug</a>
Same as above

2020-11-17 23:32 UTC, jordan-rash commented
@adthrasher This should be read to go.  Can be viewed here: https://jordan-rash.github.io/CICERO/

2020-11-18 14:15 UTC, merged